In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [29]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/data_for_eda/JD_cleaned_skills.csv")
df.head()

,Degrees,Designation,Skills,Years_of_Experience,Path
0,Bachelor's degree in Human Resources\nMaster's...,Human Resources Manager,1. Active listening\n2. Negotiation\n3. Presen...,8+ years,HR Job Description_1_Human Resources Manager.docx
1,Bachelor's degree in Finance\nBachelor's degre...,Corporate Finance Analyst,1. Spreadsheets\n2. Databases\n3. MS Office\n4...,5 to 7 years of experience,Finance Job Description_3_Corporate Finance An...
2,Bachelor's degree in Finance\nBachelor's degre...,Finance Manager,1. Proficiency in finance software\n2. Leaders...,10 years,Finance Job Description_2_Finance Manager.docx
3,Bachelor's degree in Computer Science\nBachelo...,Android Developer,1. Android SDK\n2. Android Studio\n3. Kotlin\n...,10 - 12 years of experience,IT Job Description_5_Android Developer.docx
4,Bachelor's degree in Human Resources Managemen...,Technical Recruiter,"1. Interview formats (phone, Skype, structured...",5 to 7 years,HR Job Description_3_Technical Recruiter.docx

In [27]:
print(df['Skills'])

0     Here's a list of tangible skills that can be d...
1     Here's a list of tangible skills required for ...
2     Here's a list of tangible skills mentioned in ...
3     Here's a list of tangible skills:\n\n1. Androi...
4     Here's a list of tangible skills required for ...
5     Here's a list of tangible skills required for ...
6     Here's a list of tangible skills mentioned in ...
7     Here's a list of tangible skills required for ...
8     Here's a list of tangible skills mentioned in ...
9     Here's a list of tangible skills mentioned in ...
10    Here's a list of tangible skills required for ...
11    Here's a list of tangible skills mentioned in ...
Name: Skills, dtype: object

In [ ]:
df['Skills']

0      \n\n1. PowerShell\n2. Bash\n3. Windows Server\...
1      \n\n1. Configuration of server environments (W...
2      \n\n1. Windows Server management\n2. Linux man...
3      \n\n1. Windows Server management\n2. Linux (Ce...
4      \n\n1. Server Management\n2. Network Architect...
                             ...
295    \n\n1. Python programming\n2. Java programming...
296    \n\n1. Python programming\n2. Java programming...
297    Here's a list of tangible skills directly appl...
298    \n\n1. Python programming\n2. Java programming...
299    \n\n1. Python programming\n2. Named Entity Rec...
Name: Skills, Length: 300, dtype: object

In [28]:
import pandas as pd
import re

# Load the CSV file
df = pd.read_csv('/content/drive/MyDrive/data_for_eda/JD.csv')

# Define a regex pattern to match sentences that start with "Here's a list of tangible skills"
pattern = r"Here's a list of.*?:"

# Function to remove sentences matching the pattern from the skills column
def remove_matching_sentences(text):
    # Use regex to find and remove matching sentences
    cleaned_text = re.sub(pattern, '', str(text), flags=re.IGNORECASE).strip()
    return cleaned_text

# Apply the function to the skills column
df['Skills'] = df['Skills'].apply(remove_matching_sentences)

# Save the cleaned data back to a new CSV file
cleaned_file_path = '/content/drive/MyDrive/data_for_eda/JD_cleaned_skills.csv'
df.to_csv(cleaned_file_path, index=False)

print(f"Sentences removed and new file saved as '{cleaned_file_path}'.")

Sentences removed and new file saved as '/content/drive/MyDrive/data_for_eda/JD_cleaned_skills.csv'.

In [22]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/data_for_eda/resumes_data_extraction_cleaned_skills.csv")
df.head()

,Name,Gender,Education,Last_Company,Email,LinkedIn,Phone_Number,Nationality,Designation,Degrees,Years_of_Experience,Skills,Path
0,Nur Aisyah binti Aziz,Female.,"Bachelor of Computer Science, Universiti Keban...",Maybank,nuraisyah.aziz@example.com,linkedin.com/in/nuraisyahaziz-it,+60 19-234 5678,Malaysian,Senior Systems Administrator.,Bachelor of Computer Science,19 years,1. PowerShell\n2. Bash\n3. Windows Server\n4. ...,System Administration_17.docx
1,Phuc Nguyen,Male.,"Bachelor of Science in Computer Science, Hanoi...",FPT Corporation,phuc.nguyen@example.com,linkedin.com/in/phucnguyen-it,+84 912 345 678,Vietnamese,Systems Administrator,Bachelor of Science in Computer Science,14 years,1. Configuration of server environments (Windo...,System Administration_20.docx
2,Ahmed Al-Maktoum,Male.,"Bachelor of Science in Computer Engineering, K...",Al-Futtaim Group,ahmed.almaktoum@example.com,linkedin.com/in/ahmedalmaktoum,+971 55 123 4567,Emirati.,Systems Administrator.,Bachelor of Science in Computer Engineering.,22 years,1. Windows Server management\n2. Linux managem...,Mid-Level Systems Administrator_3.docx
3,Ethan Turner,Male,"Bachelor of Information Technology, University...",Dynamic Web Hosting,ethan.turner@example.com,https://www.linkedin.com/in/ethanturner,+61 400 123 456,Australian.,Senior Systems Administrator,Bachelor of Information Technology,8.5 years.,1. Windows Server management\n2. Linux (CentOS...,Senior Systems Administrator_1.docx
4,Mehmet Yılmaz,Male,"Bachelor of Science in Information Systems, Is...",Vodafone Turkey,mehmet.yilmaz@example.com,linkedin.com/in/mehmetyilmaz-it,+90 555 123 4567,Turkish.,Systems Administrator.,Bachelor of Science in Information Systems,11 years.,1. Server Management\n2. Network Architecture\...,System Administration_19.docx

In [23]:
df['Skills']

0      1. PowerShell\n2. Bash\n3. Windows Server\n4. ...
1      1. Configuration of server environments (Windo...
2      1. Windows Server management\n2. Linux managem...
3      1. Windows Server management\n2. Linux (CentOS...
4      1. Server Management\n2. Network Architecture\...
                             ...
295    1. Python programming\n2. Java programming\n3....
296    1. Python programming\n2. Java programming\n3....
297    1. Python programming\n2. Java programming\n3....
298    1. Python programming\n2. Java programming\n3....
299    1. Python programming\n2. Named Entity Recogni...
Name: Skills, Length: 300, dtype: object

## JD unwanted text form Skills

In [ ]:
import pandas as pd
import re

# Load the CSV file
df = pd.read_csv('/content/drive/MyDrive/data_for_eda/resumes_data_extraction.csv')

# Define a regex pattern to match sentences that start with "Here's a list of tangible skills"
pattern = r"Here's a list of.*?:"

# Function to remove sentences matching the pattern from the skills column
def remove_matching_sentences(text):
    # Use regex to find and remove matching sentences
    cleaned_text = re.sub(pattern, '', str(text), flags=re.IGNORECASE).strip()
    return cleaned_text

# Apply the function to the skills column
df['Skills'] = df['Skills'].apply(remove_matching_sentences)

# Save the cleaned data back to a new CSV file
cleaned_file_path = '/content/drive/MyDrive/data_for_eda/cleaned_skills.csv'
df.to_csv(cleaned_file_path, index=False)

print(f"Sentences removed and new file saved as '{cleaned_file_path}'.")

## Change the header name of hr label csv

In [14]:
import pandas as pd

# Define the path to your CSV file
file_path = '/content/drive/MyDrive/data_for_eda/RESUME LABELS - WEB Developer.csv'

# Load the CSV file into a DataFrame
df = pd.read_csv(file_path)

# Define the new header names for the first three columns
new_header_names = ['APPLICANT NAME', 'ACCEPT/REJECT', 'REASON']

# Get the current column names
current_columns = df.columns.tolist()

# Update only the first three column headers
updated_columns = new_header_names + current_columns[3:]

# Assign the updated column names to the DataFrame
df.columns = updated_columns

# Save the updated DataFrame back to the same CSV file
df.to_csv(file_path, index=False)

print(f'Header names updated in the file: {file_path}')

Header names updated in the file: /content/drive/MyDrive/data_for_eda/RESUME LABELS - WEB Developer.csv

## Merge the hr_label with csv for EDA

csv_path: /content/drive/MyDrive/data_for_eda/cleaned_skills.csv

In [24]:
import pandas as pd

# Define file paths
files_to_compare = [
    '/content/drive/MyDrive/data_for_eda/RESUME LABELS - Android Developer (1).csv',
    '/content/drive/MyDrive/data_for_eda/RESUME LABELS - Corprate Finance Analyst.csv',
    '/content/drive/MyDrive/data_for_eda/RESUME LABELS - Data Science.csv',
    '/content/drive/MyDrive/data_for_eda/RESUME LABELS - Finance Analyst.csv',
    '/content/drive/MyDrive/data_for_eda/RESUME LABELS - Finance Manager.csv',
    '/content/drive/MyDrive/data_for_eda/RESUME LABELS - HR Manager.csv',
    '/content/drive/MyDrive/data_for_eda/RESUME LABELS - NLP_LLMs.csv',
    '/content/drive/MyDrive/data_for_eda/RESUME LABELS - Software Developer.csv',
    '/content/drive/MyDrive/data_for_eda/RESUME LABELS - Systems Administrator.csv',
    '/content/drive/MyDrive/data_for_eda/RESUME LABELS - Talent Acquisition .csv',
    '/content/drive/MyDrive/data_for_eda/RESUME LABELS - Technical recruiter.csv',
    '/content/drive/MyDrive/data_for_eda/RESUME LABELS - WEB Developer.csv'
]
cleaned_skills_path = '/content/drive/MyDrive/data_for_eda/resumes_data_extraction_cleaned_skills.csv'
new_csv_path = '/content/drive/MyDrive/data_for_eda/resumes_data_extraction_updated_cleaned_skills.csv'

# Load the cleaned_skills CSV
cleaned_skills_df = pd.read_csv(cleaned_skills_path)

# Load all resume label CSV files and concatenate them
resume_dfs = [pd.read_csv(file) for file in files_to_compare]
resume_labels_df = pd.concat(resume_dfs, ignore_index=True)

# Perform the merge operation based on 'APPLICANT NAME' and 'Name'
merged_df = pd.merge(cleaned_skills_df, resume_labels_df,
                     left_on='Name', right_on='APPLICANT NAME',
                     how='left')

# Define the order of columns in the final output
final_columns = [
    'Name', 'Gender', 'Education', 'Last_Company', 'Email', 'LinkedIn',
    'Phone_Number', 'Nationality', 'Designation', 'Degrees', 'Years_of_Experience',
    'Skills', 'Path', 'APPLICANT NAME', 'ACCEPT/REJECT', 'REASON'
]

# Reorder columns if necessary
merged_df = merged_df[final_columns]

# Save the updated DataFrame to a new CSV file
merged_df.to_csv(new_csv_path, index=False)

print(f'Updated file saved to: {new_csv_path}')

Updated file saved to: /content/drive/MyDrive/data_for_eda/resumes_data_extraction_updated_cleaned_skills.csv

remove FUllstop.

In [18]:
import pandas as pd

# Load the CSV file
file_path = '/content/drive/MyDrive/data_for_eda/resumes_data_extraction_updated_cleaned_skills.csv'
df = pd.read_csv(file_path)

# Remove trailing periods from the 'Nationality' column
df['Nationality'] = df['Nationality'].str.rstrip('.')

# Save the updated CSV file as a new file
new_file_path = '/content/drive/MyDrive/data_for_eda/resumes_data_extraction_updated_cleaned_skills_cleaned.csv'
df.to_csv(new_file_path, index=False)

In [30]:
import pandas as pd

# Load the CSV file
file_path = '/content/drive/MyDrive/data_for_eda/resumes_data_extraction_updated_cleaned_skills_cleaned.csv'
df = pd.read_csv(file_path)

# Remove trailing periods from the 'Nationality' column
df['Gender'] = df['Gender'].str.rstrip('.')

# Overwrite the original CSV file
df.to_csv(file_path, index=False)